---@class BrowserBookmarksConfig
---@field full_path boolean
---@field selected_browser Browser
---@field url_open_command string
---@field url_open_plugin? 'open_browser'|'vim_external'
---@field profile_name? string
---@field buku_include_tags boolean
---@field config_dir? string
---@field debug boolean

---@class Bookmark
---@field name string Bookmark name
---@field path string Full path from root to the name separated by '/'
---@field url string Bookmark URL
---@field tags? string Comma separated tags (only for buku)
