---@class BrowserBookmarksConfig
---@field full_path boolean
---@field selected_browser Browser
---@field url_open_command string
---@field url_open_plugin? 'open_browser'|'vim_external'
---@field profile_name? string
---@field buku_include_tags boolean
---@field config_dir? string
---@field debug boolean

---@class Bookmark
---@field name string
---@field path string
---@field url string
---@field tags? string
