---@class ConfigState
---@field os_name string
---@field os_homedir string
---@field selected_browser string
---@field url_open_command string
---@field url_open_plugin string
---@field firefox_profile_name string

---@class Bookmark
---@field name string
---@field url string
