name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Neovim ${{ matrix.neovim-version }}
    strategy:
      fail-fast: false
      matrix:
        neovim-version:
          - v0.8.3
          - v0.9.5
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}

      - name: Setup lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luarocks dependencies
        run: |
          luarocks --lua-version=5.1 install vusted
          luarocks --lua-version=5.1 install cluacov

      - name: Run tests & generate coverage report
        run: make test
        env:
          VUSTED_NVIM: ${{ steps.nvim.outputs.executable }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: luacov.report.out
